name: MyBuilder
on:
  push:
    branches: [main]
  pull_request:
    branches:
    - main
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Use node.js
      uses: actions/setup-node@v4

    - run: npm install
