name: "workflow with params"

on:
  push:
    branches: "main"

jobs:
  test_variables:
    runs-on: "ubuntu-latest"
    env:
      VARIABLE: yellow    
    
    steps:
      - run: |
          echo "${{env.VARIABLE}}"

          echo "VARIABLE=gree >> $GITHUB_ENV"

      - run: "echo ${{env.VARIABLE}}"

      - run: echo "::add-mask::Mona The Octocat"

      - run: "echo ${{env.VARIABLE}}"
      
