name: "workflow with params"
on: 
  workflow_dispatch:
    inputs:
      name:
        description: "nombre del app"
        required: true
        default: "hello man"
jobs:

  my-job:
    runs-on: "ubuntu-latest"
