name: "workflow with params"
on: 
  workflow_dispatch:
    inputs:
      my_param:
        description: "nombre del app"
        required: true
        default: "hello man"
jobs:

  my-job:
    runs-on: "ubuntu-latest"

    steps:
      - run: echo "${{ github.events.inputs.my_param }}"
