name: My first workflow

on:
  push:
    branches: 
    - "**"
  pull_request:
    branches: [ dev ]

  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js 
      uses: actions/setup-node@v4

    - run: npm install

    - run: gulp build

    - uses: actions/upload-artifact@v4
      with:
        name: MyPackage
        path: dest

    - name: Start python command

      run: print("Hola mundo")
      shell: python
